### ISSUE TITLE
duffle repo list: repos that share prefixes are listed as one

### ISSUE THREAD

**Issue by squillace** [deislabs/duffle-vscode#18]
env: 
- duffle version 70dc6f9
- Ubuntu 18.04
- duffle-vscode: 0.0.1, compiled and installed as a .vsix
- vs code: 1.26.1

For `duffle repo list`:
![image](https://user-images.githubusercontent.com/1422718/44873868-3b78d000-ac4e-11e8-9a66-d3b0ea901ada.png)

when we go to list the repos in VS code: 

![image](https://user-images.githubusercontent.com/1422718/44873910-58ad9e80-ac4e-11e8-92b4-42c9103ea002.png)

**Comment by itowlson** [comment]
Closing because we took all the repo stuff out.  And if/when we put it back in I will not do this bug again.  Or at least you'll be busy with all the _other_ bugs I do as well.
